- bin/build
- src/2023/code-of-conduct/index.html
- src/2023/index.html
- src/2023/styles/styles.css
Adds a new page with the code of conduct and links to it from the home page.
Code of conduct:
Home page changes:
| Before | After |
|--|--|
| ![Home page with social media links in the hero section](https://user-images.githubusercontent.com/677998/218321543-8ce1638d-9fb7-4e9f-9b7b-220cb65da5b5.png) | ![Home page with social media and code of conduct links in the footer](https://user-images.githubusercontent.com/677998/218321539-ee0553d4-8e04-4f08-973e-5850c9f4708a.png)
> Code of conduct

- src/2023/index.html
- src/2023/styles/styles.css
It would be nice to deploy that together with the Newsletter:
> show venue location

- src/2023/call-for-speakers/index.html
- src/2023/code-of-conduct/index.html
- src/2023/index.html
https://docs.joinmastodon.org/user/profile/#verification
> add mastadon verification

- src/2023/code-of-conduct/index.html
- src/2023/index.html
- src/2023/styles/styles.css
- src/2023/talks/index.html
This is a single page containing speaker biographies and talk abstracts.
https://github.com/MINASWAN/helvetic-ruby.ch/assets/677998/57d418b0-4dcb-4454-bc27-cacbc6b174de
> Add talks page

- src/2023/styles/styles.css
See title.
| Before | After |
|-|-|
| ![Screenshot 2023-06-28 at 06-53-59 Helvetic Ruby Conference 2023](https://github.com/MINASWAN/helvetic-ruby.ch/assets/1409672/86c961cf-e049-40d0-acd1-b95451d74f40) | ![Screenshot 2023-06-28 at 06-54-04 Helvetic Ruby Conference 2023](https://github.com/MINASWAN/helvetic-ruby.ch/assets/1409672/a1f6752f-ed93-4e7c-96b7-3ee49df37719) |
> improve partner's logo sizes on mobile

- src/2023/index.html
> Announce lightning talk CFP

- src/2023/index.html
- src/2023/location/index.html
- src/2023/schedule/index.html
- src/2023/styles/styles.css
- src/2023/talks/index.html
This early version gives a general idea of the structure of the day.
> Add schedule page

- src/2023/location/index.html
> embed map to Location page

- src/2023/schedule/index.html
This may not be the final version...
> Add talks to schedule page

- src/2023/location/index.html
- src/2023/styles/styles.css
Adding details about how to get to Bern from the Airports.
> add details about arrival from abroad

- src/2023/index.html
> Remove call for proposals for lightning talks

- src/2023/index.html
> Add LinkedIn logo with the link to the event

- src/2024/call-for-speakers/index.html
- src/2024/index.html
- src/2024/location/index.html
- src/2024/schedule/index.html
- src/2024/sponsorships/index.html
- src/2024/styles/styles.css
> Add sponsorships page

- src/2024/sponsorships/index.html
- Add a link to email on sponsorship page
> Make email a link

- src/2024/index.html
> Add AppSignal to sponsors

- src/2024/index.html
- Adds direct link to speakers list: helvetic-ruby.ch/src/2024/index.html#speakers
> Add direct link to speakers list

- src/2024/index.html
> Add call for lightning talks

- src/2024/index.html
- src/2024/styles/styles.css
> Add end of early bird sales banner

- src/2024/index.html
- src/2024/styles/styles.css
- responsive, adds video to the main page
> Add Helvetic Ruby 2023 video to main page

- src/2024/index.html
- src/2024/location/index.html
Some recommendations off the top of my head.
I also added a table of contents. It's nice to have most travel information on the same page, but the page is getting long.
> Add recommendations for restaurants, bars and sights

- src/2024/talks/index.html
> Add missing speaker name

- src/2024/schedule/index.html
> Add conference day schedule

- src/2024/schedule/index.html
I'll add more maintainers to the list of participants as they confirm.
> Add details about Thursday activities

- src/2024/index.html
- src/2024/schedule/index.html
Still subject to change depending on the weather and the number of participants.
> Add details about Saturday plans

- src/2024/schedule/index.html
Now breaks are explicitly listed.
> Add breaks to the schedule

- src/2024/schedule/index.html
> Add maintainers to Open Source Office Hours

- src/2024/schedule/index.html
> Update after party schedule

- src/2024/index.html
> Announce date for Helvetic Ruby 2025

- _includes/footer.html
- sponsorships/index.html
> Define 2025 sponsorship packages

- location/index.html
> Add Rhodania hotel as recommendation

- _includes/header.html
- index.html
- styles/styles.css
> Add early bird banner (and workshops id)

- schedule/index.html
> De-emphasize community space in favour of workshops

- _includes/footer.html
- index.html
> Open CFP for 2025 lightning talks

- index.html
- styles/styles.css
> Tweak AppSignal logo size

- index.html
> Add Deplo.io as a bronze sponsor

- schedule/index.html
| Before | After |
-- | --
| <img width="762" alt="image" src="https://github.com/user-attachments/assets/dbc71904-24ff-4745-8377-64085ec168d1" /> |  <img width="762" alt="image" src="https://github.com/user-attachments/assets/38ae5309-1385-48d3-ac1a-f280205e0623" />
> Update the Friday morning schedule
